### ISSUE TITLE
child_remove listening

### ISSUE THREAD

**Issue by stigmat4j** [tiberiuc/redux-react-firebase#13]
``` js
@firebase((props) => {
  return [
    [`${props.userId}/friends`]
  ]
})
```

this code not working. "Invalid path"
I need child_remove listening

**Comment by RahavLussato** [comment]
Hi,
you need to do something like this : 

```
@firebase((props) => {
  [`${props.userId}/friends`]
})
@connect(
    (state, props) => ({
        friendsSnapshot: snapshotToJS(state.firebase,
        `${props.userId}/friends`)}),
    {})
```

and for remove listening you can use : this.props.firebase.unWatchEvent.

Invalid path means that either you didn't login before with firebase.login() or you misspelled your path.

**Comment by RahavLussato** [comment]
@tiberiuc i think you can close this since @stigmat4j didn't response
