### ISSUE TITLE
Could you give me feedback on my previous solution?

### ISSUE THREAD

**Issue by wordyallen** [tiberiuc/redux-react-firebase#14]
It was a basic Firebase middleware:

``` js
const fbMiddleware = store => next => action => {
    const result = next(action);
    if(action.type!=='SET_STATE'){
        firebaseRef.update(store.getState().toJS())
    }
}


const  store = createStore(reducer, applyMiddleware(thunk, fbMiddleware))
```

**Comment by RahavLussato** [comment]
this way every action (not only fb) will be catch by this middleware, and you using only update method.
you don't have the full functionality like queries, listening to real events ....

if the reason for working like that is only for update fb on every CRUD operation, please change the if to be opt-in and not opt-out (maybe by using some CRUD actions convention) and add error handling to that. 

also by using opt-in you'll have the option to update only the new part from the state and not taking all the state every time, what will cause you troubles when the state will grow.

**Comment by wordyallen** [comment]
thanks
