### ISSUE TITLE
Docs unclear/suggestion

### ISSUE THREAD

**Issue by TrySpace** [tiberiuc/redux-react-firebase#15]
Going into this, I thought this was going to be similar to `redux-storage-engine-localstorage`, which is my fault, but perhaps partially the documentations'. 

I'm curious why there are no dispatchers used, at least not in the user's code, only in the `src`. The code-example omits the fact that direct calls to Firebase are made, and then changes would come back to the `store` which works, but I don't understand this approach as it circumvents a more "reduxy" way of having dispatchers initiate changes, to avoid bugs, inconsistencies and confusion.

It's also very confusing when the example code is missing half of the code that makes it work, and misleading, as from the example-code I assumed dispatches where used when making changes.
For example the `handleAdd` function definition is not shown, only in example source, where it turns out it does a plain `firebase.push`, which is fine, but not what I expected when I read the initial docs.

What I expected was, I dispatch an action, it changes something in the local `store`, and at the same time updates it in firebase. The main problem is when I use multiple middlewares, like localstorage, I want to prevent having to `dispatch` _and_ update firebase everytime, these should be unified.

I understand that how it is now, listeners are being placed, so the top store is always up to date.

What I would suggest is at least one example of how to use this in conjunction with `dispatch`, instead of calling firebase directly, like mentioned above, having this work with some sort of `middleware` and use `set` `push` and `remove`.

Or an example of how to use it with `mapStateToProps, mapDispatchToProps` ?

Maybe I'm completely wrong about these approaches, but it's just an idea..

**Comment by dcworldwide** [comment]
I've just read through the examples.. 

> What I expected was, I dispatch an action, it changes something in the local store, and at the same time updates it in firebase. The main problem is when I use multiple middlewares, like localstorage, I want to prevent having to dispatch and update firebase everytime, these should be unified.

This was one of the first things I picked up on as well. Firebase should be abstracted from the component as much as possible. So hiding firebase query / mutation logic from components makes sense to me.

**Comment by RahavLussato** [comment]
@TrySpace as i see it and if i understood @tiberiuc correct the main idea behind this lib is to have the ability to get realtime data from firebase, the other direction options as update/insert data to firebase was not on the main scope so @tiberiuc opened this options by give you the ability to call directly to firebase.

i agree with you that have "the other direction" as middleware instead of calling directly to fire base will take this lib forward, and you can always feel free to open PR :)

**Comment by TrySpace** [comment]
I would suggest having a few default actions in this lib to mutate data like:

```
{
    type: 'SET_FIREBASE_DATA',
    path: '/users/profile/image',
    value: 'imgurl.com/image.jpg'
}
```

Or maybe it's better to have to build your **own, more specific** actions like:

```
{
  type: 'SET_PROFILE_IMAGE'
  value: 'imgurl.com/image.jpg'
}
```

And have a more central place to define all the paths and its different purposes, sort of like a model/schema definition like swagger or I forgot the other one.

Anyways, this is something that might evolve from this hopefully. Because at the moment, I can't get my current setup to work with this, that might be because I'm using a localstorage atm, but also like I said, the docs could do with a little brushing up. But I'm not the one to do this, as I didn't contribute any code, so have no understanding of its workings, so no PR for me any time soon.

**Comment by tiberiuc** [comment]
@Tryspace, thank you very much for suggestions. As  @RahavLussato said , the main scope of that library was to get realtime data from firebase. To mutate data you don't need actions as you can do it like this:

```
@firebase()
......
const {firebase} = this.props
firebase.set('/users/profile/image', 'imgurl.com/image.jpg')
// --- OR ---
firebase.push('/todos', {data})
```

that will save data into database and will auto trigger the child_changed and update your store. This is running pretty fast as firebase library also have a cache implemented so the store is update immediate and will not wait for back and forth to the database.

I think creating a specific type of actions for profile for example and add a place to define path for that actions just add too much complexity to the library and it will make it less flexible, but probably I'm wrong.

Also @TrySpace you are right about the docs, it should be more clear , I'm just not very good on writing it, but I wil try

**Comment by RahavLussato** [comment]
@tiberiuc if i not mistake the docs changed from the time @TrySpace wrote this issue.
Can you close this ?
