### ISSUE TITLE
How to log a user in when testing?

### ISSUE THREAD

**Issue by ghost** [tiberiuc/redux-react-firebase#16]
I'm trying to test a component whose layout changes depending on whether a user is logged in. My Mocha tests looks like this:

```
import {Provider} from 'react-redux';
import TestUtils from 'react-addons-test-utils';
import expect from 'expect.js'
import newStore from './store';
import MyComponent from './MyComponent.jsx';

describe('MyComponent', function() {

  context('when the user is logged in', function() {
    var component;

    beforeEach(function() {
      // initialize the Redux store
      var store = newStore({ gameID: 'a001' });

      // log a user in programmatically - but how to do it?

      // render the component under test
      component = TestUtils.renderIntoDocument(
        <Provider store={store}>
          <Game />
        </Provider>
      );
    });

    it("should show the user's name", function() {
      var playerNameDisplay = TestUtils.findRenderedDOMComponentWithClass(
        component, 'player-name'
      );
      expect(playerNameDisplay.textContent).to.be('My Name');
    });

    /* and all the rest of the tests... */
  });
});
```

I'm not really sure how to log a user in during test setup. First I tried to just set the user profile by initializing the store with a profile in place:

```
beforeEach(function() {
  // initialize the Redux store - with a profile set!
  var store = newStore({ gameID: 'a001', firebase: { profile: { name: 'My Name' }}});

  // render the component under test
  component = TestUtils.renderIntoDocument(
    <Provider store={store}>
      <Game />
    </Provider>
  );
});
```

but when the component under test rendered, the profile data was gone. Looks like it gets reset.

Then I tried to find a way to call the `createUser` and `login` methods provided by `redux-react-firebase` in the test setup, but couldn't figure out how to get a reference to the object that has those methods:

```
beforeEach(() => {
      // initialize the Redux store
      var store = newStore({ gameID: 'a001' });

      // log a user in programmatically
      var credentials = {
        email: 'a@a.a',
        password: 'a'
      };
      var firebase = // but how to get a reference?
      firebase.createUser(credentials, { name: 'My Name' });
      firebase.login(credentials);

      // render the component under test
      component = TestUtils.renderIntoDocument(
        <Provider store={store}>
          <Game />
        </Provider>
});
```

Is there a way to get a reference in my test setup to the object `createUser` and `login` are defined on? Or am I going about logging a user in all wrong? Any guidance would be very helpful, I'm stuck.

**Comment by tiberiuc** [comment]
Hi ,

If I correctly understand this is what you need:

```
const createStoreWithFirebase = compose(
    reduxReactFirebase('YOUR_FIREBASE_URL', {userProfile: 'users'}),
)(createStore)
```

basicaly you tell the lib to auto fetch the profile user when somebody login . Data will be get from `/users/<userId>` and will be placed into the store in `firebase.profile` 

if you keep your user profile in a different place in your database you can configure that in userProfile

let me know if that is what you need

**Comment by ghost** [comment]
Well, I was hoping there would be a way to set user data in the store directly without going out to Firebase, just to keep the unit tests as lightweight as possible. But if it's necessary to do user setup in Firebase then I can implement that.

**Comment by tiberiuc** [comment]
Actually you can do it if you want for testing

try to dispatch a message like that: 

```
dispatch({
        type: '@@reactReduxFirebase/SET_PROFILE',
        profile: { ---YOUR_USER_PROFILE_OBJECT--- }
      })
```

of course you can create an action for that if you want

there are some other stuff you can do like LOGIN:

```
dispatch({
        type: '@@reactReduxFirebase/LOGIN',
        auth: { uid: ..., ...},
        authError: null
      })
```

or LOGOUT

```
dispatch({
        type: '@@reactReduxFirebase/LOGOUT'
      })
```

or LOGIN ERROR

```
dispatch({
        type: '@@reactReduxFirebase/LOGIN_ERROR',
        authError: 'the error message'
      })
```

see the actions.js and constants.js for more details

let me know how that work

**Comment by ghost** [comment]
Ah, perfect! That's exactly what I was trying to implement.

**Comment by tiberiuc** [comment]
excellent, I will close this issue
