### ISSUE TITLE
Issue when bunding with webpack

### ISSUE THREAD

**Issue by prescottprue** [tiberiuc/redux-react-firebase#18]
I got the following errors when trying to use with webpack. I tried using both `noParse` as well as setting an alias to both the source folder and the build folder.

![screen shot 2016-06-04 at 2 16 17 am](https://cloud.githubusercontent.com/assets/2992224/15798794/8cb83dc6-29fa-11e6-9e2c-98e709de83f9.png)

I was able to get it working by installing `bluebird` and `immutable` into my project, but it might be nice to make those become dependencies or be part of the docs somewhere.

**Comment by RahavLussato** [comment]
@prescottprue  which npm version you use ?
i see that immutable is listed as peer dependency so you must to install that (in the newer versions of npm peer dependencies is not installed automatically), you also need to install bluebird.
@tiberiuc we need to add bluebird as peer dependency.

**Comment by tiberiuc** [comment]
thank you  @RahavLussato 
I also added bluebird as peer dependency

**Comment by tiberiuc** [comment]
as @RahavLussato said you need to install immutable and bluebird

```
npm install --save bluebird immutable
```

**Comment by prescottprue** [comment]
Yeah, installing is what I had to do to fix it, but figured it should be included as a dep.

Thanks for making it a peer dependency @tiberiuc.
