### ISSUE TITLE
Advanced use question

### ISSUE THREAD

**Issue by vladtar** [tiberiuc/redux-react-firebase#19]
Hi,

Thank you for creating this package. I have enjoyed using it so far.

There is a scenario I'm trying that I'm having trouble with. I have a component that requires an array of items for a specific user that comes from firebase. The list of item keys is listed under the user in firebase, so my initial watch looks something like:

``` js
@firebase(
    props => [
        `users/${props.userId}/items`
    ]
)
```

which gives me the list of item keys for that user. I then need to query those items themselves from firebase from `/items` by key. What is the preferred / recommended way to do this?

Initially I tried passing the array of keys to a lower component but that didn't work since `@firebase()` doesn't retrigger when `props` get updated, and the keys array was empty at first.

Thank you in advance.

**Comment by tiberiuc** [comment]
you are right, when props get changed firebase events don't re-trigger which is a bug, I will try to fix it as soon as possible as I already encountered in one of my projects

**Comment by vladtar** [comment]
Awesome. Thank you. Go Romania!!
