### ISSUE TITLE
connect stop working with minified bundle

### ISSUE THREAD

**Issue by RahavLussato** [tiberiuc/redux-react-firebase#2]
you can delete this one it was issue on my configuration

**Comment by tiberiuc** [comment]
sure, no problem , can you tell me what config issue was, maybe I can include it in the docs to be more clear

**Comment by RahavLussato** [comment]
oh it was my fault :blush: , i forgot to add "reduxReactFirebase" to store on create store on my all envs.
(did it only for dev)

**Comment by tiberiuc** [comment]
thank you very much for clarifying
