### ISSUE TITLE
this.props.firebase undefined, this.props.store.firebase is not.

### ISSUE THREAD

**Issue by TrySpace** [tiberiuc/redux-react-firebase#21]
When I follow the example as close as possible, I'm stuck when I try to define:

`{ firebase } = this.props`

From exampe: https://github.com/tiberiuc/redux-react-firebase/blob/master/example/App.js

My component has no `this.props.firebase`, it does have `this.props.store.firebase`

My reducer (reducers/index): 

```
Redux                    = require 'redux'
{ combineReducers }      = Redux
{ firebaseStateReducer } = require 'redux-react-firebase'
visibilityFilter         = require './visibilityFilter'

combinedReducer = combineReducers({
  visibilityFilter: visibilityFilter,
  firebase: firebaseStateReducer
})
```

I assume that's where `this.props.store.firebase` comes from.
Then in the file where I put the `Provider` component:

```
reducers = require './reducers/index'

firebaseRef           = reduxReactFirebase('https://xxx.firebaseio.com/', { 'userProfile', 'users'} )
composedStore         = compose(firebaseRef)(createStore)
store                 = composedStore(reducers , {})
...
// then later:
 ReactDOM.render(
    <Provider store={store}>
           <App store={cubeStore.getState()} />
    </Provider

```

Then, when I inspect `Provider` with React devtools: 

```
   Object 
    dispatch: dispatch(action)
    firebase: Object 
    getState: getState()
    replaceReducer: replaceReducer(nextReducer)
    subscribe: subscribe(listener)
    Symbol(observable):observable()
```

This looks good, and `firebase` contains `_`, `helpers`, and `ref`

But this is in `this.props.store.firebase`, not in `this.firebase` like the example suggests.

However, then I try to connect firebase to one of my containers, and it gets a context `store`, and also `this.state.storeState` which is not documented anywhere.

```
{ firebase, helpers }           = require 'redux-react-firebase'
{ isLoaded, isEmpty, dataToJS } = helpers

firebase = firebase(['test']).bind(this)
connect(({firebase}) => ({
    test: dataToJS(firebase, 'test'),
  })
).bind(this)

https://github.com/tiberiuc/redux-react-firebase/issues/20

```

`this.state.storeState` contains `_root` and a `size` prop, in that `Connect`ed element.

Now main problem is, that I can't use `firebase.set()` like intended from the examples, and I'm sure I shouldn't manually extract it from the `context.store.firebase.helpers`?

(As a sidenote, while browsing through the source, I don't understand the `import Firebase from 'firebase'` in https://github.com/tiberiuc/redux-react-firebase/blob/master/source/index.js, I don't see it is ever used there?)

**Comment by tiberiuc** [comment]
to be able to access `this.props.firebase` you need to use @firebase() before connect just like that

```
@firebase()
@connect( 
  ....
)
```

that will add firebase object to your props so you don;t need to access the context ( the decorator is doing that for you )

the firebase object contains set, push , remove functions  and here is how are they defined:

```
    const set = (path, value, onComplete) => ref.child(path).set(value, onComplete)
    const push = (path, value, onComplete) => ref.child(path).push(value, onComplete)
    const remove = (path, onComplete) => ref.child(path).remove(onComplete)
    const watchEvent = (eventName, eventPath) => Actions.watchEvent(firebase, dispatch, eventName, eventPath, true)
    const unWatchEvent = (eventName, eventPath, queryId=undefined) => Actions.unWatchEvent(firebase, eventName, eventPath, queryId)
    const login = credentials => Actions.login(dispatch, firebase, credentials)
    const logout = () => Actions.logout(dispatch, firebase)
    const createUser = (credentials, profile) => Actions.createUser(dispatch, firebase, credentials, profile)
    const resetPassword = (credentials) => Actions.resetPassword(dispatch, firebase, credentials)
    const changePassword = (credentials) => Actions.changePassword(dispatch, firebase, credentials)
```

if you want to access the original root firebase you can use `firebase.ref` and you can use it like that `firebase.ref.child( .... )`

let me know if you have questions

**Comment by TrySpace** [comment]
How would I do this without the decorator?
Mainly because right now I can't convert code to es6 yet and I want to understand what the decorator does.

**Comment by tiberiuc** [comment]
here is where it is defined

https://github.com/tiberiuc/redux-react-firebase/blob/master/source/connect.js

line 65

basically what is does it is creating another component wrapping current component and add some functionality to it. First it will add firebase object into props ( line 103 ) then passed on the defined paths will add the necessary events ( line 88 and 89 ) and when the component will unmount will unwatch the events ( line 94 )

without ES6 you should use it like

```
var MyComponent = React.createClass({
   ....
})

var FirebaseConnectedMyComponent = firebase( [] )( MyComponent )

module.exports = FirebaseConnectedMyComponent
```

to connect to redux it will look like:

```
var MyComponent = React.createClass({
   ....
})

var ReduxConnectedMyComponent = connect( mapStateToProps )( MyComponent )
var FirebaseConnectedMyComponent = firebase( [] )( ReduxConnectedMyComponent )

module.exports = FirebaseConnectedMyComponent
```

BTW, never tested that way
