### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by sedubois** [tiberiuc/redux-react-firebase#22]
I have a package.json with `firebase@3.0.4`, `bluebird@3.4.0`. When installing `redux-react-firebase`, it complains that these peer dependencies aren't met (expecting lower versions). Will it be updated to support latest libraries?

**Comment by RahavLussato** [comment]
you can see on the readme on "In the future" section : 
`Add support for new Firebase version ( lib ver 3.x )`

**Comment by sedubois** [comment]
OK, thanks
