### ISSUE TITLE
Update to Firebase 3.x.x

### ISSUE THREAD

**Issue by mrshll** [tiberiuc/redux-react-firebase#23]
Sad that the API has significant changes, but so things go. I've been using [re-base](https://github.com/tylermcginnis/re-base) but I love to play with your library. Do you have a plan for update?

**Comment by prescottprue** [comment]
+1 especially on using re-base in the meantime

It seems like @tiberiuc is planning on including this in the future, but hasn't stated when. I am currently working on this, and am hoping to make a PR within the next 2-3 weeks.

**Comment by prescottprue** [comment]
[My Fork](https://github.com/prescottprue/redux-react-firebase) Currently works on v3.x.x. Still working out some final kinks before creating a PR here. @mmoutenot Care to give it a try and see what works/doesn't work for you? That way we can provide a completely working version for merging.

**Comment by mrshll** [comment]
Yep. I've been using the core functionality for a few weeks now. I'll try
to cover more this weekend

**Comment by prescottprue** [comment]
@mmoutenot I created a PR, but thinking of getting another library name on npm to publish to in the meantime in case @tiberiuc doesn't want to move to v3+ of Firebase.

**Comment by prescottprue** [comment]
I was informed that the original creator of this library is going to be busy for the next little while. Here is my thoughts, which I also [posted to redux-firebase](https://github.com/colbyr/redux-firebase/issues/2).

## Current Libraries
- [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase) - Current defacto solution but owner is busy for a few months
- [firedux](https://github.com/adjohnson916/firedux) - supports v3.0.4
- [refire](https://www.npmjs.com/package/refire) - easily configurable firebase bindings
- [redux-firebase](https://github.com/colbyr/redux-firebase) - best namespace, but out of date
- [react-firebase](https://github.com/unfold/react-firebase) - Similar to react-redux, good docs

_There might be more, this is all I could find on initial search_

## Working Solution
- [fork working with v3](https://github.com/prescottprue/redux-react-firebase)
- [PR with working version](https://github.com/tiberiuc/redux-react-firebase/pull/27)

**Note:** Directly including this git repo will not work with npm as it does not include the built code

Are we interested in combining all of these libraries? I use this stuff daily, so I will be constantly improving the library if we all get centered around one. I am more than willing to spear head the project and handle fielding incoming issues/PRS.

**Comment by mrshll** [comment]
@prescottprue used it a lot yesterday - hopefully you saw some of my changes. Many are unimportant and me getting it to work with react-native. Others are crucial like auth fixes and the database ref.

Great research on all of these repos. I will look more at firedux tonight! I agree, and am down to team up with you on whatever we pick as the best one to move forward with. Tired of npm install'ing from my github fork.

**Comment by prescottprue** [comment]
@mmoutenot +1 on the installing from the fork. My fork doesn't include the source code either, so I have had to build it locally and `npm link`. 

The changes you made to my fork are great, thanks! Contacted the other library owners to see if they are interested in combining as well. I think that the best overall name would be redux-firebase, but that namespace seems to be the oldest of all the libraries, so not sure if we can get read/write access to that.

Not sure if everyone here is on the [Firebase Slack](firebase-community.slack.com), but there is a Redux channel there. Might be good to have discussion there so we don't have to leave an issue open in this repo.

**Comment by prescottprue** [comment]
Created [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3) to make this available on npm for now.

**Comment by tiberiuc** [comment]
Hi everyone, sorry for being off that much time due to some family problems, it is great to see new projects raising for my project.

I am interested to add data mapping for this project and also interested in merging them in one project if everyone it is interested

@prescottprue I totally agree redux-firebase it is the best name for this project and having so many different projects will get people confused and also contribute to js fatigue.

any ideas are welcome

**Comment by mrshll** [comment]
Never apologize for time away for an open source project! Hope everything is well and glad you're back.

`redux-firebasev3` has been good to me so far, and I'm happy to help with future changes. What is the data mapping you are referring to?

**Comment by prescottprue** [comment]
@tiberiuc I agree with @mmoutenot, never apologize for time off! Stoked to know that you are on into the idea of combining libraries. I have seen at least 10+ libraries that all seem to solve this same need.

Created a [redux-firebase gitter](https://gitter.im/redux-firebase/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) so we can keep these discussions going. Everyone is welcome!
