### ISSUE TITLE
Redux Dev Tools

### ISSUE THREAD

**Issue by brandonmikeska** [tiberiuc/redux-react-firebase#26]
Will this work with redux dev tools and redux-react-router?

**Comment by tiberiuc** [comment]
sure it is working, I'm already using in a couple of projects

**Comment by brandonmikeska** [comment]
My bad, does it work out of the box or is it passed in the options param when configuring the store?

**Comment by tiberiuc** [comment]
redux-react-firebase it is only for connecting firebase if you need redux dev tools or react-redux-router you need to add them to your store as you normally do
