### ISSUE TITLE
Logout erases all data

### ISSUE THREAD

**Issue by simonrozsival** [tiberiuc/redux-react-firebase#31]
When the user logs out of the app, **all** the data is removed by the reducer. This does not work for me and I think this behaviour isn't really that convenient for other purposes. I want some of the data to remain in the state and I cannot think of a good way of achieving that.

**Comment by tiberiuc** [comment]
currently there is no way to achieve that, but I think we can implement that into the library.

Do you have any suggestion ?

**Comment by simonrozsival** [comment]
Well I would suggest to add a parameter to the logout action, which would tell which parts of the tree to preserve and which to remove... To make it backwards compatible, an array (default value - empty array) of paths, which would remain untouched, would be passed as a parameter. I will try to make a pull request tomorrow.

**Comment by tiberiuc** [comment]
thank you for your pull request
