### ISSUE TITLE
`reduxReactFirebase` function does not pass through `enhancer` argument of `createStore`

### ISSUE THREAD

**Issue by pcardune** [tiberiuc/redux-react-firebase#36]
Per the [redux docs for createStore](http://redux.js.org/docs/api/createStore.html), you can pass in an optional third argument for `createStore`, which is commonly used to apply middlewares. Following the example in the README, this doesn't work as expected because `reduxReactFirebase` only returns a `createStore` function that accepts two arguments.

For example, when using the [thunk middleware](https://github.com/gaearon/redux-thunk):

``` jsx
import {createStore, combineReducers, compose, applyMiddleware} from 'redux'
import {reduxReactFirebase, firebaseStateReducer} from 'redux-react-firebase'
import thunkMiddleware from 'redux-thunk'

const rootReducer = combineReducers({
  firebase: firebaseStateReducer
})
const config = {
  apiKey: '<your-api-key>',
  authDomain: '<your-auth-domain>',
  databaseURL: '<your-database-url>',
  storageBucket: '<your-storage-bucket>'
}
const createStoreWithFirebase = compose(
    reduxReactFirebase(config),
)(createStore)

const middlewares = applyMiddleware(thunkMiddleware)
const store = createStoreWithFirebase(rootReducer, initialState, middlewares)
```

the middlewares argument does not actually get passed through to redux's `createStore` function.

**Comment by d-winter** [comment]
Any plans when this will be fixed?
Shouldn't it be a simple addition within the compose.js?:

```
return next => (reducer, initialState) => {
    const defaultConfig = {
      userProfile: null
    }
    const store = next(reducer, initialState)
```

to 

```
  return next => (reducer, initialState, middleware) => {
    const defaultConfig = {
      userProfile: null
    }
    const store = next(reducer, initialState, middleware)
```

**Comment by tiberiuc** [comment]
Can you create a pull request please

**Comment by rpeterson** [comment]
PR submitted for this.

**Comment by tiberiuc** [comment]
thank you, PR merged
