### ISSUE TITLE
_reduxReactFirebase.firebase.storage is not a function(…)

### ISSUE THREAD

**Issue by gazpachu** [tiberiuc/redux-react-firebase#39]
How can I access the `storage` using the `redux-react-firebase` object? With the original firebase NPM works fine.

I'm trying like this: `let imgRef = firebase.storage().child('posts/' + post.slug + '.jpg');`

Thanks

**Comment by tiberiuc** [comment]
currently you can't, but I will try to add this or you can make a PR

**Comment by RahavLussato** [comment]
@tiberiuc my pr #40 is solving that.

**Comment by RahavLussato** [comment]
@tiberiuc you can close this after you merged my PR

**Comment by gazpachu** [comment]
@RahavLussato I've installed the latest version 2.3.5 (which includes your PR), but it doesn't seem to fix it completely. Is this change supposed to fix it? https://github.com/tiberiuc/redux-react-firebase/pull/40/commits/5d5669212cf4cd73962d66d343e3b5a88c5144ff#diff-a4200fc012ab1991422a051d08eeaf5d

Now I have this error:

`TypeError: firebase.storage(...).child is not a function`

And this is the snippet I'm using to load an image from firebase storage:

```
let imgRef = firebase.storage().child(type + '/' + item.slug + '.jpg');
    imgRef.getDownloadURL().then(function(url) {
        this.refs[className+'-'+id+'-img'].src = url;
    }.bind(this)).catch(function(error) {
        console.log(error);
});
```

It's the same procedure as in the official Firebase storage download file full example: https://firebase.google.com/docs/storage/web/download-files

**Comment by RahavLussato** [comment]
@gazpachu its because the child function is not on storage is on storageref you need to change your code to something like:

```
let storageRef =  firebase.storage().ref();

let imgRef = storageRef.child(type + '/' + item.slug + '.jpg');
    imgRef.getDownloadURL().then(function(url) {
        this.refs[className+'-'+id+'-img'].src = url;
    }.bind(this)).catch(function(error) {
        console.log(error);
});
```

https://firebase.google.com/docs/storage/web/create-reference

**Comment by gazpachu** [comment]
@RahavLussato thanks! it worked :)

**Comment by RahavLussato** [comment]
@tiberiuc you can close this

**Comment by gazpachu** [comment]
@RahavLussato somehow, this stopped working: `this.storageRef = firebase.storage().ref();`

I'm getting now `TypeError: _reduxReactFirebase.firebase.storage is not a function`

**Comment by RahavLussato** [comment]
@gazpachu try to get firebase from props `this.props.firebase` and don't forget to use the firebase decorator.
