### ISSUE TITLE
query with the decorator?

### ISSUE THREAD

**Issue by mmahalwy** [tiberiuc/redux-react-firebase#4]
is there a way to query? for example, first 5.

**Comment by tiberiuc** [comment]
not yet , but that is a work in progress

**Comment by tiberiuc** [comment]
that is a work in progress, I don't have a time estimate right now but hope to do it very soon as it is one of the most requested feature and I also need it in one of my projects

**Comment by tiberiuc** [comment]
just added queries support  thanks to @RahavLussato 
orderByChild
limitToFirst
limitToLast
startAt
endAt

ex
```
@firebase([
  'todos#startAt=5&limitToFirst=2'
])
```

**Comment by tiberiuc** [comment]
thanks to @RahavLussato 
orderByChild
limitToFirst
limitToLast
startAt
endAt

ex

```
@firebase([
  'todos#startAt=5&limitToFirst=2'
])
```
