### ISSUE TITLE
orderByChild parses to int

### ISSUE THREAD

**Issue by fscottfoti** [tiberiuc/redux-react-firebase#41]
Hi guys - 

First off great work - I'm finding the library to be super useful.

I do notice that you force values to ints [here](https://github.com/tiberiuc/redux-react-firebase/blob/6af415509239450e75407805fa87c39e771581b0/source/actions.js#L139).  When I to an orderByChild("something").equalTo("someString") is doesn't work - I mean the children are strings even though in some cases the strings do actually parse as ints.  Anyway, I can take out the parseInt and things work as I expect them to.  What do you think about an option to not coerce to int?  Given that you're using query strings, maybe something like doNotParse=1??

**Comment by RahavLussato** [comment]
Hi, i wrote the parsing part.
I did it because when i used that and gave the decorator string that is originally int on firebase.
I understand what you say and flag as you suggested will solve your issue.
Can you submit a new PR that will not break the current behavior by using default params ?

**Comment by fscottfoti** [comment]
Yes, I'll take a look.

**Comment by fscottfoti** [comment]
I actually found a workaround on my end (changed type to int!) so probably don't need to fix this in the short term.  I will close for now.

**Comment by RahavLussato** [comment]
#52
