### ISSUE TITLE
Rationale behind `data` path?

### ISSUE THREAD

**Issue by Domiii** [tiberiuc/redux-react-firebase#42]
From the beginning this confused me a bit: For some reason, this library (and I think I also saw it in other libraries) gave special significance to the `/data` path, specifically by offering the [`dataToJS` convenience helper function](https://github.com/tiberiuc/redux-react-firebase/blob/master/API.md#datatojsimmutabledata-pathasstring-notsetvalue). From what I understand, the `/data` path has no special significance to Firebase per se, so, if I am not utterly wrong, this is based on some sort of convention, isn't it?

Seeing how your library gives special attention to the `/data` path, references to documents which propose the convention of structuring your data in Firebase like this would be greatly appreciated, not sure if you or anyone else could provide those?

(Slightly off-topic: In general, any sort of list of resources and conventions that help new-comers better structure their data right from the start, would love to hear about it :) )

**Comment by RahavLussato** [comment]
DataToJS is not related to /data path on firebase, its just a way to get snapshot.val() directly, if you need to iterate over your snapshot by some order you did with query you'll not use that and do snapshot.foreach, if not its nicer to get the data directly.

**Comment by Domiii** [comment]
@RahavLussato It specifically states in [the API description](https://github.com/tiberiuc/redux-react-firebase/blob/master/API.md#datatojsimmutabledata-pathasstring-notsetvalue) (and it is an accurate description of [the code](https://github.com/tiberiuc/redux-react-firebase/blob/master/source/helpers.js#L27)):

> dataToJS(immutableData, pathAsString, notSetValue)
>> Short for pathToJS(immutableData, `data/${pathAsString}`, notSetValue)

It is the same as `pathToJS` but restricted to the `/data` path. So I am wondering: What is the significance of the `/data` path? Why did it deserve hard-coding? What are the conventions?

Sorry for not being clear earlier! :)

**Comment by RahavLussato** [comment]
The /data that mentioned is related to the internal state of redux where the data is stored not to the path of firebase

**Comment by RahavLussato** [comment]
@Domiii can @tiberiuc close this ?

**Comment by Domiii** [comment]
Ok thank you.

**Comment by RahavLussato** [comment]
close #42
