### ISSUE TITLE
Can't get my firebase data.

### ISSUE THREAD

**Issue by jonathandion** [tiberiuc/redux-react-firebase#5]
Hi, I can't get my data from firebase using @connect. Also I'm using react router to pass my params.

There is my code :

`@firebase( [
  'fishes'
])
@connect(
  (state, props) => ({
    fishes: dataToJS(state.firebase,`/${props.params.storeId}/fishes`)
  })
)`

props.params.storeId is equal to 'itchy-drab-leaves' from the url.

My firebase url look like this : https://fishes-store.firebaseio.com/itchy-drab-leaves

but I can send data to firebase with push :
`firebase.push(`${this.params.storeId}/fishes`, data)`

What I'm doing wrong ? 

Thanks !

**Comment by tiberiuc** [comment]
so you are trying to get /fishes from firebase ( that is what `@firebase(['fishes'])` is doing )
but from the store you are trying to get /${storedId}/fishes ( different path )

I can't see your database but I think the code should be like this

```
@firebase( (props) => ([
 `${props.params.storeId}/fishes` 
]))
@connect( 
  (state, props) => ({ 
       fishes: dataToJS(state.firebase,`${props.params.storeId}/fishes')
 }) )
```

**Comment by jonathandion** [comment]
Hey I tried your solution and I still receive `undefined`.

There is all my info 
- Name of my Firebase : FISHES-STORE
- url : https://fishes-store.firebaseio.com/
- Screenshot preview [here](https://www.dropbox.com/s/2xs9utrlqcs0v3z/Screen%20Shot%202016-03-05%20at%208.20.00%20AM.png?dl=0)

**App.js**

``` javascript
const rootReducer = combineReducers({
    routing: routerReducer,
    firebase: firebaseStateReducer,
})

const createStoreWithFirebase = compose(
    reduxReactFirebase('https://fishes-store.firebaseio.com/'),
)(createStore)

const state = {}
const store = createStoreWithFirebase(rootReducer, state)`
```

**Fishes.js**

``` javascript
@firebase( (props) => ([
 `${props.params.storeId}/fishes`
]))
@connect(
  (state, props) => ({
     fishes: dataToJS(state.firebase,`${props.params.storeId}/fishes`)
 })
)
```

Before I was using [re-base](https://github.com/tylermcginnis/re-base) and it was working correctly with the same url.

``` javascript
const storeId = this.props.params.storeId;
const options = {
    endpoint: `${storeId}/fishes`,
    context : this, // App component
    state : 'fishes'
}
```

Thanks for the help.

**Comment by tiberiuc** [comment]
I can't reproduce it m can you make a simple example which reproduce it and I can run it on my computer to debug it ?
