### ISSUE TITLE
Rename or close repo

### ISSUE THREAD

**Issue by nijotz** [tiberiuc/redux-react-firebase#73]
SOOOOO many time my coworkers and I have confused this repo for the real one. GO AWAY 👎  I just spent a half hour reading the wrong docs. You owe me money 💰

**Comment by tiberiuc** [comment]
With all the respect, this was the original repo and it was the first one. The repo you are referring to it was a clone of this one and it is using a similar name

**Comment by nijotz** [comment]
All right, all right. I apologize tiberian. Cheers.

**Comment by tiberiuc** [comment]
it is ok, no problem, it is also my fault, I should write I don’t update this repo and people should also look on the other one which is more updated. I promise I will do that

**Comment by nijotz** [comment]
🍝
